#version: '3.8'

services:
  web_service:
    image: spp_smks_pgri6_mlg:1.0.0
    ports:
      - target: 8080
        published: 10102
        mode: ingress
    volumes:
      - ./source/storage/:/var/www/html/storage/  # Bind mount for storage directory
    environment:
      DB_HOST: 192.168.0.34  # Change to your external MySQL host (IP or domain)
      DB_PORT: 3306  # Default MySQL port, change if necessary
      DB_DATABASE: spp_smks_pgri6_mlg
      DB_USERNAME: aries
      DB_PASSWORD: Salam1jiwa
    # Limit default logging container
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
        mode: non-blocking