#version: '3.8'

services:
  web_service:
    image: spp_smks_pgri6_mlg:1.0.0
    ports:
      - target: 8082
        published: 9002
        mode: ingress
    volumes:
      - ./source/storage:/var/www/html/storage  # Bind mount directory storage
    # Limit default logging container
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
        mode: non-blocking
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8102:80"  # Exposing port 80 inside the container to port 8102 on host
      - "443:443"  # If you plan to use HTTPS as well
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    depends_on:
      - web_service
