#version: '3.8'

services:
  web_service:
    image: spp_smks_pgri6_mlg:1.0.0
    networks:
      - erayadigitalnetwork
    ports:
      - target: 8080
        published: 10102
        mode: ingress
    volumes:
      - ./source/storage/:/var/www/html/storage/
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 192.168.0.34
      DB_PORT: 8808
      DB_DATABASE: eds_smks_pgri6_mlg
      DB_USERNAME: aries
      DB_PASSWORD: Salam1jiwa
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
        mode: non-blocking

networks:
  default:
    name: erayadigitalnetwork
    external: true
